import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/layout/navbar/navbar";
import BackgroundProvider from "@/components/BackgroundProvider";
import SessionWrapper from "@/providers/SessionWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased flex-col flex w-screen h-screen">
        <SessionWrapper>
          <BackgroundProvider>
            <div className="h-16 w-full">
              <Navbar />
            </div>
            {children}
          </BackgroundProvider>
        </SessionWrapper>
      </body>
    </html>
  );
}
